"""
IMPORTANT: this file is automatically generated by the LLM, it needs to be reworked.
"""

from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from pyrogram.types import Chat, Message, MessageReactions
from rich.progress import Progress

from telegram_cleaner.formatting import Formatter
from telegram_cleaner.cleaner import Cleaner


# Create a mock Config class
class MockConfig:
    def __init__(self):
        self.LANG = "en"
        self.API_ID = 12345
        self.API_HASH = "mock_hash"


@pytest.fixture(autouse=True)
def mock_config(mocker):
    mocker.patch("telegram_cleaner.config.get_config", return_value=MockConfig())
    return MockConfig()


# Helper function to create mock chats
def create_mock_chat(chat_id, title=None):
    chat = MagicMock(spec=Chat)
    chat.id = chat_id
    chat.title = title or f"Chat {chat_id}"
    chat.type = "private"  # Default to private chat
    return chat


# Helper function to create mock messages
def create_mock_message(msg_id, date=None, reactions=None):
    msg = MagicMock(spec=Message)
    msg.id = msg_id
    # Set a default date if none provided
    if date is None:
        date = datetime.now(timezone.utc)
    msg.date = date
    msg.text = f"Message {msg_id}"

    if reactions:
        reaction = MagicMock()
        reaction.chosen_order = 1
        msg.reactions = MessageReactions(reactions=[reaction])
    else:
        msg.reactions = None

    return msg


# Create a mock progress object
@pytest.fixture
def mock_progress():
    return MagicMock(spec=Progress)


@pytest.fixture
def cleaner(mocker):
    # Create a mock cleaner with mocked __init__
    mocker.patch.object(Cleaner, "__init__", return_value=None)
    cleaner = Cleaner()
    # Set up necessary attributes
    cleaner.lang = "en"
    cleaner.message_ids = {}
    cleaner.reaction_ids = {}
    cleaner.formatter = MagicMock(spec=Formatter)
    cleaner.formatter.format_chat_name.return_value = "Chat 1"
    cleaner.formatter.format_export_line.return_value = "Export line"
    cleaner.client = MagicMock()
    # Add missing attributes
    cleaner.export_buffer = MagicMock()
    cleaner.REACTION_EPOCH = MagicMock()
    cleaner.REACTION_EPOCH.replace.return_value = cleaner.REACTION_EPOCH
    return cleaner


@pytest.fixture(autouse=True)
def mock_translations(mocker):
    # Mock the _ (translation) function to avoid config calls
    mocker.patch("telegram_cleaner.main._", return_value="")
    return
