"""
IMPORTANT: this file is automatically generated by the LLM, it needs to be reworked.
"""

from datetime import datetime, timedelta, timezone
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, call, mock_open, patch

import pytest
from pyrogram.types import Chat

from conftest import create_mock_chat, create_mock_message
from hypothesis import assume, given, settings
from hypothesis import strategies as st
from pyrogram.enums import ChatType
from pyrogram.errors import FloodWait, RPCError

from telegram_cleaner.actions import Action, ActionPicker
from telegram_cleaner.constants import EXPORT_DIR, REACTION_EPOCH
from telegram_cleaner.export import ExportBuffer
from telegram_cleaner.formatting import Formatter


class TestCleaner:
    """Test the main Cleaner class functionality."""

    @pytest.fixture
    def mock_client(self):
        client = AsyncMock()
        client.search_messages = AsyncMock()
        client.get_chat_history = AsyncMock()
        client.delete_messages = AsyncMock()
        client.send_reaction = AsyncMock()
        client.leave_chat = AsyncMock()
        return client

    @pytest.fixture
    def cleaner_with_mocks(self, cleaner, mock_client):
        cleaner.client = mock_client
        cleaner.console = MagicMock()
        return cleaner

    @pytest.mark.asyncio
    async def test_export_messages_empty_chat(self, cleaner_with_mocks, mock_progress):
        """Test exporting messages from an empty chat."""
        chat = create_mock_chat(123, "Test Chat")

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        # Return the async-generator when the method is called
        cleaner_with_mocks.client.search_messages = lambda *a, **kw: AsyncIterator([])

        await cleaner_with_mocks._export_messages(chat, mock_progress)

        # Verify no messages were added to export buffer
        assert cleaner_with_mocks.export_buffer.add.call_count == 0
        # Verify progress was updated correctly
        mock_progress.add_task.assert_called_once()
        mock_progress.update.assert_called()

    @pytest.mark.asyncio
    async def test_export_messages_with_data(self, cleaner_with_mocks, mock_progress):
        """Test exporting messages with actual data and formatting."""
        chat = create_mock_chat(123, "Test Chat")

        # Create mock messages with different timestamps
        messages = [
            create_mock_message(1, datetime(2023, 1, 1, 12, 0, tzinfo=timezone.utc)),
            create_mock_message(2, datetime(2023, 1, 2, 13, 30, tzinfo=timezone.utc)),
            create_mock_message(3, datetime(2023, 1, 3, 14, 45, tzinfo=timezone.utc)),
        ]

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        cleaner_with_mocks.client.search_messages = lambda *a, **kw: AsyncIterator(
            messages
        )

        await cleaner_with_mocks._export_messages(chat, mock_progress)

        # Verify all messages were exported with correct action
        assert cleaner_with_mocks.export_buffer.add.call_count == 3
        export_calls = cleaner_with_mocks.export_buffer.add.call_args_list
        for call_args in export_calls:
            assert call_args[0][0] == Action.EXPORT_MESSAGES

        # Verify message IDs were stored
        assert cleaner_with_mocks.message_ids[123] == [1, 2, 3]
        # Verify export buffer flush was called at the end
        cleaner_with_mocks.export_buffer.flush.assert_called()

    # @pytest.mark.asyncio
    # @given(st.integers(min_value=101, max_value=500))
    # @settings(max_examples=5,)
    # async def test_export_messages_batch_flushing(self, cleaner_with_mocks, mock_progress, message_count):
    #     """Test that export buffer is flushed every 100 messages."""
    #     chat = create_mock_chat(123, "Large Chat")
    #
    #     messages = [create_mock_message(i) for i in range(message_count)]
    #
    #     class AsyncIterator:
    #         def __init__(self, items):
    #             self.items = items
    #
    #         def __aiter__(self):
    #             return self
    #
    #         async def __anext__(self):
    #             if not self.items:
    #                 raise StopAsyncIteration
    #             return self.items.pop(0)
    #
    #     cleaner_with_mocks.client.search_messages = lambda *a, **kw: AsyncIterator(messages)
    #
    #     await cleaner_with_mocks._export_messages(chat, mock_progress)
    #
    #     # Verify flush was called for every 100 messages plus final flush
    #     expected_flush_calls = (message_count // 100) + 1
    #     assert cleaner_with_mocks.export_buffer.flush.call_count == expected_flush_calls
    #
    # @pytest.mark.asyncio
    # async def test_export_reactions_filters_by_epoch(self, cleaner_with_mocks, mock_progress):
    #     """Test that reactions are only exported for messages after REACTION_EPOCH."""
    #     chat = create_mock_chat(123, "Test Chat")
    #
    #     # Messages before and after REACTION_EPOCH
    #     old_date = REACTION_EPOCH - timedelta(days=1)
    #     new_date = REACTION_EPOCH + timedelta(days=1)
    #
    #     messages = [
    #         create_mock_message(1, date=old_date, reactions=True),  # Too old, should be ignored
    #         create_mock_message(2, date=new_date, reactions=True),  # Should be exported
    #         create_mock_message(3, date=new_date, reactions=False),  # No chosen reaction
    #     ]
    #
    #     class AsyncIterator:
    #         def __init__(self, items):
    #             self.items = items
    #
    #         def __aiter__(self):
    #             return self
    #
    #         async def __anext__(self):
    #             if not self.items:
    #                 raise StopAsyncIteration
    #             return self.items.pop(0)
    #
    #     cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(messages)
    #
    #     await cleaner_with_mocks._export_reactions(chat, mock_progress)
    #
    #     # Should export only the message after REACTION_EPOCH with chosen reaction
    #     assert cleaner_with_mocks.export_buffer.add.call_count == 1
    #     assert cleaner_with_mocks.reaction_ids[123] == [2]
    #
    #     # Verify correct action type
    #     export_calls = cleaner_with_mocks.export_buffer.add.call_args_list
    #     assert export_calls[0][0][0] == Action.EXPORT_REACTIONS

    @pytest.mark.asyncio
    async def test_export_reactions_batch_processing(
        self, cleaner_with_mocks, mock_progress
    ):
        """Test that reactions export flushes buffer every 200 scanned messages."""
        chat = create_mock_chat(123, "Large Chat")

        # Create 250 messages, every 5th has a chosen reaction
        messages = []
        for i in range(250):
            has_reaction = i % 5 == 0
            msg = create_mock_message(
                i + 1, date=REACTION_EPOCH + timedelta(days=1), reactions=has_reaction
            )
            messages.append(msg)

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(
            messages
        )

        await cleaner_with_mocks._export_reactions(chat, mock_progress)

        # Should flush at 200 scanned messages and at the end
        assert cleaner_with_mocks.export_buffer.flush.call_count >= 2
        # Should export 50 reactions (every 5th message)
        assert cleaner_with_mocks.export_buffer.add.call_count == 50

    @pytest.mark.asyncio
    async def test_delete_messages_chunking(self, cleaner_with_mocks, mock_progress):
        """Test that messages are deleted in chunks of 100 (Telegram limit)."""
        chat = create_mock_chat(123, "Test Chat")

        # Set up 250 message IDs (should result in 3 chunks: 100, 100, 50)
        message_ids = list(range(1, 251))
        cleaner_with_mocks.message_ids[123] = message_ids

        await cleaner_with_mocks._delete_messages(chat, mock_progress)

        # Should be called 3 times
        assert cleaner_with_mocks.client.delete_messages.call_count == 3

        # Verify chunk sizes and chat_id
        calls = cleaner_with_mocks.client.delete_messages.call_args_list
        assert calls[0][0][0] == 123  # chat_id
        assert len(calls[0][0][1]) == 100  # First chunk size
        assert len(calls[1][0][1]) == 100  # Second chunk size
        assert len(calls[2][0][1]) == 50  # Last chunk size

        # Verify all message IDs were included
        all_deleted_ids = []
        for call_args in calls:
            all_deleted_ids.extend(call_args[0][1])
        assert sorted(all_deleted_ids) == message_ids

    @pytest.mark.asyncio
    async def test_delete_messages_with_sleep(self, cleaner_with_mocks, mock_progress):
        """Test that there's a pause between delete operations."""
        chat = create_mock_chat(123, "Test Chat")

        # Set up enough messages for multiple chunks
        cleaner_with_mocks.message_ids[123] = list(range(1, 201))

        with patch("asyncio.sleep") as mock_sleep:
            await cleaner_with_mocks._delete_messages(chat, mock_progress)

            # Should sleep after each chunk (2 times for 200 messages)
            assert mock_sleep.call_count == 2
            mock_sleep.assert_called_with(0.3)

    @pytest.mark.asyncio
    async def test_delete_messages_fallback_search(
        self, cleaner_with_mocks, mock_progress
    ):
        """Test fallback to searching when no cached message IDs exist."""
        chat = create_mock_chat(123, "Test Chat")

        # No cached message IDs
        cleaner_with_mocks.message_ids = {}

        # Mock search to return some messages
        messages = [create_mock_message(i) for i in range(1, 6)]

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        # Create a wrapper that tracks calls but returns async iterator
        original_search_messages = cleaner_with_mocks.client.search_messages

        def search_wrapper(*args, **kwargs):
            # Record the call on the original mock
            original_search_messages(*args, **kwargs)
            # Return the async iterator
            return AsyncIterator(messages)

        cleaner_with_mocks.client.search_messages = search_wrapper

        await cleaner_with_mocks._delete_messages(chat, mock_progress)

        # Should search for messages first
        original_search_messages.assert_called_once_with(chat_id=123, from_user="me")
        # Then delete them
        cleaner_with_mocks.client.delete_messages.assert_called_once_with(
            123, [1, 2, 3, 4, 5]
        )

    @pytest.mark.asyncio
    async def test_delete_reactions_cached_ids(self, cleaner_with_mocks, mock_progress):
        """Test reaction deletion using cached IDs."""
        chat = create_mock_chat(123, "Test Chat")

        # Set up cached reaction IDs
        cleaner_with_mocks.reaction_ids[123] = [10, 20, 30]

        await cleaner_with_mocks._delete_reactions(chat, mock_progress)

        # Should send empty reaction for each cached ID
        assert cleaner_with_mocks.client.send_reaction.call_count == 3
        calls = cleaner_with_mocks.client.send_reaction.call_args_list

        for i, call_args in enumerate(calls):
            assert call_args[0][0] == 123  # chat_id
            assert call_args[0][1] == [10, 20, 30][i]  # message_id
            assert call_args[0][2] == ""  # empty reaction

    # @pytest.mark.asyncio
    # async def test_delete_reactions_handles_rpc_errors(self, cleaner_with_mocks, mock_progress):
    #     """Test that RPCError during reaction deletion is handled gracefully."""
    #     chat = create_mock_chat(123, "Test Chat")
    #
    #     cleaner_with_mocks.reaction_ids[123] = [1, 2, 3]
    #
    #     # Mock send_reaction to raise RPCError for middle message
    #     async def mock_send_reaction(chat_id, msg_id, reaction):
    #         if msg_id == 2:
    #             raise RPCError("Message not found")
    #
    #     cleaner_with_mocks.client.send_reaction.side_effect = mock_send_reaction
    #
    #     # Should not raise exception
    #     await cleaner_with_mocks._delete_reactions(chat, mock_progress)
    #
    #     # Should attempt all 3 reactions
    #     assert cleaner_with_mocks.client.send_reaction.call_count == 3

    @pytest.mark.asyncio
    async def test_delete_reactions_scan_mode(self, cleaner_with_mocks, mock_progress):
        """Test reaction deletion in scan mode when no cached IDs."""
        chat = create_mock_chat(123, "Test Chat")

        # No cached IDs – force scan mode
        cleaner_with_mocks.reaction_ids = {}

        # Create three messages after REACTION_EPOCH, two of them with a chosen reaction
        new_date = REACTION_EPOCH + timedelta(days=1)
        messages = [
            create_mock_message(1, date=new_date, reactions=True),  # Should delete
            create_mock_message(2, date=new_date, reactions=False),  # Should skip
            create_mock_message(3, date=new_date, reactions=True),  # Should delete
        ]

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(
            messages
        )

        await cleaner_with_mocks._delete_reactions(chat, mock_progress)

        # Only messages 1 and 3 have chosen reactions → 2 calls expected
        assert cleaner_with_mocks.client.send_reaction.call_count == 2
        expected_ids = {1, 3}
        called_ids = {
            c.args[1] for c in cleaner_with_mocks.client.send_reaction.call_args_list
        }
        assert called_ids == expected_ids

    @pytest.mark.asyncio
    async def test_delete_reactions_sleep_on_batch(
        self, cleaner_with_mocks, mock_progress
    ):
        """Test that _delete_reactions sleeps after every 100 processed reactions."""
        chat = create_mock_chat(123, "Test Chat")

        cleaner_with_mocks.reaction_ids = {}  # ensure scan mode

        # 150 messages with chosen reactions to trigger one sleep (after the first 100)
        new_date = REACTION_EPOCH + timedelta(days=1)
        messages = [
            create_mock_message(i, date=new_date, reactions=True) for i in range(150)
        ]

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(
            messages
        )

        with patch("asyncio.sleep", AsyncMock()) as mock_sleep:
            await cleaner_with_mocks._delete_reactions(chat, mock_progress)

            # For 150 deletions there should be exactly one sleep call (after 100)
            assert mock_sleep.await_count == 1
            mock_sleep.assert_awaited_with(0.1)

    @pytest.mark.asyncio
    async def test_process_chat_action_order(self, cleaner_with_mocks, mock_progress):
        """Test that chat processing follows correct action order."""
        chat = create_mock_chat(123, "Test Chat")

        actions = [
            Action.EXPORT_REACTIONS,
            Action.EXPORT_MESSAGES,
            Action.DELETE_REACTIONS,
            Action.DELETE_MESSAGES,
        ]

        # Mock the individual methods to track call order
        call_order = []

        async def mock_export_reactions(c, p):
            call_order.append("export_reactions")

        async def mock_export_messages(c, p):
            call_order.append("export_messages")

        async def mock_delete_reactions(c, p):
            call_order.append("delete_reactions")

        async def mock_delete_messages(c, p):
            call_order.append("delete_messages")

        cleaner_with_mocks._export_reactions = mock_export_reactions
        cleaner_with_mocks._export_messages = mock_export_messages
        cleaner_with_mocks._delete_reactions = mock_delete_reactions
        cleaner_with_mocks._delete_messages = mock_delete_messages

        await cleaner_with_mocks._process_chat(chat, actions, mock_progress)

        # Verify correct order: exports first, then deletions
        expected_order = [
            "export_reactions",
            "export_messages",
            "delete_reactions",
            "delete_messages",
        ]
        assert call_order == expected_order

    @pytest.mark.asyncio
    async def test_perform_final_actions_leave_group(self, cleaner_with_mocks):
        """Test leaving group chats."""
        group_chat = create_mock_chat(123, "Test Group")
        group_chat.type = ChatType.GROUP

        supergroup_chat = create_mock_chat(456, "Test Supergroup")
        supergroup_chat.type = ChatType.SUPERGROUP

        actions = [Action.LEAVE_GROUP]

        await cleaner_with_mocks._perform_final_actions(group_chat, actions)
        await cleaner_with_mocks._perform_final_actions(supergroup_chat, actions)

        # Should leave both group types
        expected_calls = [call(123), call(456)]
        cleaner_with_mocks.client.leave_chat.assert_has_calls(expected_calls)

    @pytest.mark.asyncio
    async def test_perform_final_actions_delete_private_both(self, cleaner_with_mocks):
        """Test deleting private chat for both parties."""
        chat = create_mock_chat(123, "Private User")
        chat.type = ChatType.PRIVATE

        actions = [Action.DELETE_PRIVATE_BOTH]

        # Mock chat history
        messages = [create_mock_message(i) for i in range(1, 6)]

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(
            messages
        )

        await cleaner_with_mocks._perform_final_actions(chat, actions)

        # Should delete all messages with revoke=True
        cleaner_with_mocks.client.delete_messages.assert_called_once()
        call_args = cleaner_with_mocks.client.delete_messages.call_args
        assert call_args[1]["chat_id"] == 123
        assert call_args[1]["message_ids"] == [1, 2, 3, 4, 5]
        assert call_args[1]["revoke"] is True

    @pytest.mark.asyncio
    async def test_perform_final_actions_delete_private_self(self, cleaner_with_mocks):
        """Test deleting private chat for self only."""
        chat = create_mock_chat(123, "Private User")
        chat.type = ChatType.PRIVATE

        actions = [Action.DELETE_PRIVATE_SELF]

        await cleaner_with_mocks._perform_final_actions(chat, actions)

        # Should leave chat with delete=True
        cleaner_with_mocks.client.leave_chat.assert_called_once_with(123, delete=True)

    @pytest.mark.asyncio
    async def test_perform_final_actions_no_private_actions_for_groups(
        self, cleaner_with_mocks
    ):
        """Test that private chat actions are ignored for group chats."""
        chat = create_mock_chat(123, "Test Group")
        chat.type = ChatType.GROUP

        actions = [Action.DELETE_PRIVATE_BOTH, Action.DELETE_PRIVATE_SELF]

        await cleaner_with_mocks._perform_final_actions(chat, actions)

        # Should not call any deletion methods
        cleaner_with_mocks.client.delete_messages.assert_not_called()
        cleaner_with_mocks.client.leave_chat.assert_not_called()


class TestExportBuffer:
    """Test the ExportBuffer class."""

    @pytest.fixture
    def mock_console(self):
        return MagicMock()

    @pytest.fixture
    def export_buffer(self, mock_console):
        return ExportBuffer(console=mock_console)

    def test_add_and_flush_single_action(self, export_buffer):
        """Test adding lines and flushing for a single action."""
        with patch("builtins.open", mock_open()) as mock_file, patch(
            "telegram_cleaner.export.datetime"
        ) as mock_datetime:
            mock_datetime.now.return_value.strftime.return_value = "20231201-143000"

            export_buffer.add(Action.EXPORT_MESSAGES, "Test line 1")
            export_buffer.add(Action.EXPORT_MESSAGES, "Test line 2")

            export_buffer.flush()

            # Should create file with timestamp
            expected_path = EXPORT_DIR / "export_messages_20231201-143000.txt"
            mock_file.assert_called_once_with(expected_path, "w", encoding="utf-8")

            # Should write both lines
            handle = mock_file.return_value.__enter__.return_value
            handle.write.assert_called_once_with("Test line 1\nTest line 2\n")

    def test_flush_multiple_actions(self, export_buffer):
        """Test flushing multiple action types."""
        with patch("builtins.open", mock_open()) as mock_file, patch(
            "telegram_cleaner.export.datetime"
        ) as mock_datetime:
            mock_datetime.now.return_value.strftime.return_value = "20231201-143000"

            export_buffer.add(Action.EXPORT_MESSAGES, "Message line")
            export_buffer.add(Action.EXPORT_REACTIONS, "Reaction line")

            export_buffer.flush()

            # Should create two files
            assert mock_file.call_count == 2

            # Verify file paths
            calls = mock_file.call_args_list
            file_paths = [call[0][0] for call in calls]
            expected_paths = [
                EXPORT_DIR / "export_messages_20231201-143000.txt",
                EXPORT_DIR / "export_reactions_20231201-143000.txt",
            ]
            assert set(file_paths) == set(expected_paths)

    def test_flush_append_mode(self, export_buffer):
        """Test that subsequent flushes append to existing files."""
        with patch("builtins.open", mock_open()) as mock_file, patch(
            "telegram_cleaner.export.datetime"
        ) as mock_datetime:
            mock_datetime.now.return_value.strftime.return_value = "20231201-143000"
            expected_path = EXPORT_DIR / "export_messages_20231201-143000.txt"

            # First flush
            export_buffer.add(Action.EXPORT_MESSAGES, "Line 1")
            export_buffer.flush()

            # Mock that file now exists
            with patch.object(Path, "exists", return_value=True):
                # Second flush
                export_buffer.add(Action.EXPORT_MESSAGES, "Line 2")
                export_buffer.flush()

            # Should open in append mode on second flush
            calls = mock_file.call_args_list
            assert calls[0][0] == (
                expected_path,
                "w",
            )  # First call with 'w'
            assert calls[1][0] == (
                expected_path,
                "a",
            )  # Second call with 'a'

    def test_empty_flush(self, export_buffer, mock_console):
        """Test that flushing with no data doesn't create files."""
        with patch("builtins.open", mock_open()) as mock_file:
            export_buffer.flush()

            # Should not create any files
            mock_file.assert_not_called()
            # Should not print file creation message
            mock_console.print.assert_not_called()


class TestActionPicker:
    """Test the ActionPicker class."""

    def test_get_available_actions_private_only(self):
        """Test available actions for private chats only."""
        private_chat = create_mock_chat(123, "User")
        private_chat.type = ChatType.PRIVATE

        actions = ActionPicker.get_available_actions([private_chat])

        expected_actions = [
            Action.EXPORT_REACTIONS,
            Action.EXPORT_MESSAGES,
            Action.DELETE_REACTIONS,
            Action.DELETE_MESSAGES,
            Action.DELETE_PRIVATE_SELF,
            Action.DELETE_PRIVATE_BOTH,
        ]
        assert set(actions) == set(expected_actions)
        assert Action.LEAVE_GROUP not in actions

    def test_get_available_actions_groups_only(self):
        """Test available actions for group chats only."""
        group_chat = create_mock_chat(123, "Group")
        group_chat.type = ChatType.GROUP

        supergroup_chat = create_mock_chat(456, "Supergroup")
        supergroup_chat.type = ChatType.SUPERGROUP

        actions = ActionPicker.get_available_actions([group_chat, supergroup_chat])

        expected_actions = [
            Action.EXPORT_REACTIONS,
            Action.EXPORT_MESSAGES,
            Action.DELETE_REACTIONS,
            Action.DELETE_MESSAGES,
            Action.LEAVE_GROUP,
        ]
        assert set(actions) == set(expected_actions)
        assert Action.DELETE_PRIVATE_SELF not in actions
        assert Action.DELETE_PRIVATE_BOTH not in actions

    def test_get_available_actions_mixed_chats(self):
        """Test available actions for mixed chat types."""
        private_chat = create_mock_chat(123, "User")
        private_chat.type = ChatType.PRIVATE

        group_chat = create_mock_chat(456, "Group")
        group_chat.type = ChatType.GROUP

        actions = ActionPicker.get_available_actions([private_chat, group_chat])

        # Should include all possible actions
        expected_actions = [
            Action.EXPORT_REACTIONS,
            Action.EXPORT_MESSAGES,
            Action.DELETE_REACTIONS,
            Action.DELETE_MESSAGES,
            Action.LEAVE_GROUP,
            Action.DELETE_PRIVATE_SELF,
            Action.DELETE_PRIVATE_BOTH,
        ]
        assert set(actions) == set(expected_actions)

    @patch("telegram_cleaner.actions.inquirer.prompt")
    def test_pick_actions_user_selection(self, mock_prompt):
        """Test action picking with user selection."""
        chats = [create_mock_chat(123, "Test Chat")]

        # Mock user selecting some actions
        mock_prompt.return_value = {
            "actions": [Action.EXPORT_MESSAGES, Action.DELETE_MESSAGES]
        }

        selected_actions = ActionPicker.pick(chats)

        assert selected_actions == [Action.EXPORT_MESSAGES, Action.DELETE_MESSAGES]

        # Verify prompt was called correctly
        mock_prompt.assert_called_once()
        prompt_args = mock_prompt.call_args[0][0][0]
        assert prompt_args.name == "actions"

    @patch("telegram_cleaner.actions.inquirer.prompt")
    def test_pick_actions_no_selection(self, mock_prompt):
        """Test action picking when user makes no selection."""
        chats = [create_mock_chat(123, "Test Chat")]

        # Mock user canceling or selecting nothing
        mock_prompt.return_value = None

        selected_actions = ActionPicker.pick(chats)

        assert selected_actions == []


class TestFormatter:
    """Test the Formatter class."""

    def test_format_chat_name_with_title(self):
        """Test formatting chat name when title is available."""
        chat = create_mock_chat(123, "My Group Chat")
        chat.title = "My Group Chat"

        result = Formatter.format_chat_name(chat)

        assert result == "My Group Chat"

    def test_format_chat_name_private_full_name(self):
        """Test formatting private chat name with first and last name."""
        chat = create_mock_chat(123)
        chat.title = None
        chat.first_name = "John"
        chat.last_name = "Doe"

        result = Formatter.format_chat_name(chat)

        assert result == "John Doe"

    def test_format_chat_name_private_first_only(self):
        """Test formatting private chat name with first name only."""
        chat = create_mock_chat(123)
        chat.title = None
        chat.first_name = "John"
        chat.last_name = None

        result = Formatter.format_chat_name(chat)

        assert result == "John"

    def test_format_chat_name_private_empty_names(self):
        """Test formatting when names are empty."""
        chat = create_mock_chat(123)
        chat.title = None
        chat.first_name = ""
        chat.last_name = ""

        result = Formatter.format_chat_name(chat)

        assert result == ""

    def test_format_message_preview_text_message(self):
        """Test formatting message preview for text messages."""
        message = create_mock_message(1)
        message.text = "This is a test message with some content"
        message.caption = None

        result = Formatter.format_message_preview(message)

        assert result == "This is a test message with some content"

    def test_format_message_preview_caption_message(self):
        """Test formatting message preview for messages with captions."""
        message = create_mock_message(1)
        message.text = None
        message.caption = "Photo caption here"

        result = Formatter.format_message_preview(message)

        assert result == "Photo caption here"

    def test_format_message_preview_long_text_truncation(self):
        """Test that long messages are truncated to 200 characters."""
        message = create_mock_message(1)
        long_text = "A" * 250  # 250 characters
        message.text = long_text
        message.caption = None

        result = Formatter.format_message_preview(message)

        assert len(result) == 200
        assert result == "A" * 200

    def test_format_message_preview_newline_replacement(self):
        """Test that newlines are replaced with spaces."""
        message = create_mock_message(1)
        message.text = "Line 1\nLine 2\nLine 3"
        message.caption = None

        result = Formatter.format_message_preview(message)

        assert result == "Line 1 Line 2 Line 3"
        assert "\n" not in result

    def test_format_message_preview_empty_message(self):
        """Test formatting empty messages."""
        message = create_mock_message(1)
        message.text = None
        message.caption = None

        result = Formatter.format_message_preview(message)

        assert result == ""

    # def test_format_export_line_complete(self):
    #     """Test complete export line formatting."""
    #     chat = create_mock_chat(123, "Test Chat")
    #
    #     # Create message with specific timestamp
    #     test_date = datetime(2023, 12, 1, 14, 30, 45, tzinfo=timezone.utc)
    #     message = create_mock_message(42, date=test_date)
    #     message.text = "Test message content"
    #
    #     with patch.object(test_date, 'astimezone') as mock_astimezone:
    #         # Mock the local timezone conversion
    #         local_date = MagicMock()
    #         local_date.strftime.return_value = "2023-12-01 14:30:45"
    #         mock_astimezone.return_value = local_date
    #
    #         result = Formatter.format_export_line(chat, message)
    #
    #         expected = "[2023-12-01 14:30:45] Test Chat | id=42 | Test message content"
    #         assert result == expected


class TestReactionEpochHandling:
    """Test proper handling of REACTION_EPOCH across the system."""

    @pytest.fixture
    def mock_client(self):
        client = AsyncMock()
        client.search_messages = AsyncMock()
        client.get_chat_history = AsyncMock()
        client.delete_messages = AsyncMock()
        client.send_reaction = AsyncMock()
        client.leave_chat = AsyncMock()
        return client

    @pytest.fixture
    def cleaner_with_mocks(self, cleaner, mock_client):
        cleaner.client = mock_client
        cleaner.console = MagicMock()
        return cleaner

    # @pytest.mark.asyncio
    # async def test_reaction_epoch_boundary(self, cleaner_with_mocks, mock_progress):
    #     """Reactions exactly at the epoch threshold should be processed."""
    #     chat = create_mock_chat(123, "Test Chat")
    #
    #     before_epoch = REACTION_EPOCH - timedelta(seconds=1)
    #     at_epoch = REACTION_EPOCH
    #     after_epoch = REACTION_EPOCH + timedelta(seconds=1)
    #
    #     messages = [
    #         create_mock_message(1, date=before_epoch, reactions=True),  # Should be ignored
    #         create_mock_message(2, date=at_epoch, reactions=True),      # Should be exported
    #         create_mock_message(3, date=after_epoch, reactions=True),   # Should be exported
    #     ]
    #
    #     class AsyncIterator:
    #         def __init__(self, items):
    #             self.items = items
    #
    #         def __aiter__(self):
    #             return self
    #
    #         async def __anext__(self):
    #             if not self.items:
    #                 raise StopAsyncIteration
    #             return self.items.pop(0)
    #
    #     cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(messages)
    #
    #     await cleaner_with_mocks._export_reactions(chat, mock_progress)
    #
    #     # Only messages at/after the epoch should be exported
    #     assert cleaner_with_mocks.export_buffer.add.call_count == 2
    #     assert cleaner_with_mocks.reaction_ids[chat.id] == [2, 3]
    #
    # @pytest.mark.asyncio
    # async def test_reaction_deletion_respects_epoch(self, cleaner_with_mocks, mock_progress):
    #     """Test that reaction deletion also respects REACTION_EPOCH in scan mode."""
    #     chat = create_mock_chat(123, "Test Chat")
    #     cleaner_with_mocks.reaction_ids = {}  # Force scan mode
    #
    #     before_epoch = REACTION_EPOCH - timedelta(days=1)
    #     after_epoch = REACTION_EPOCH + timedelta(days=1)
    #
    #     messages = [
    #         create_mock_message(1, date=before_epoch, reactions=True),  # Should skip
    #         create_mock_message(2, date=after_epoch, reactions=True),  # Should delete
    #     ]
    #
    #     class AsyncIterator:
    #         def __init__(self, items):
    #             self.items = items
    #
    #         def __aiter__(self):
    #             return self
    #
    #         async def __anext__(self):
    #             if not self.items:
    #                 raise StopAsyncIteration
    #             return self.items.pop(0)
    #
    #     cleaner_with_mocks.client.get_chat_history = lambda *a, **kw: AsyncIterator(messages)
    #
    #     await cleaner_with_mocks._delete_reactions(chat, mock_progress)
    #
    #     # Should only attempt to delete reaction from message after epoch
    #     assert cleaner_with_mocks.client.send_reaction.call_count == 1
    #     cleaner_with_mocks.client.send_reaction.assert_called_with(123, 2, "")


class TestErrorHandling:
    """Test error handling and edge cases."""

    @pytest.fixture
    def mock_client(self):
        client = AsyncMock()
        client.search_messages = AsyncMock()
        client.get_chat_history = AsyncMock()
        client.delete_messages = AsyncMock()
        client.send_reaction = AsyncMock()
        client.leave_chat = AsyncMock()
        return client

    @pytest.fixture
    def cleaner_with_mocks(self, cleaner, mock_client):
        cleaner.client = mock_client
        cleaner.console = MagicMock()
        return cleaner

    @pytest.mark.asyncio
    async def test_flood_wait_handling(self, cleaner_with_mocks, mock_progress):
        """Test that FloodWait errors are handled appropriately."""
        chat = create_mock_chat(123, "Test Chat")
        cleaner_with_mocks.message_ids[123] = [1, 2, 3]

        # Mock delete_messages to raise FloodWait on first call
        flood_error = FloodWait(value=30)
        cleaner_with_mocks.client.delete_messages.side_effect = [
            flood_error,
            None,
            None,
        ]

        # This should raise FloodWait as the code doesn't handle it currently
        with pytest.raises(FloodWait):
            await cleaner_with_mocks._delete_messages(chat, mock_progress)

    # @pytest.mark.asyncio
    # async def test_various_rpc_errors_in_reactions(self, cleaner_with_mocks, mock_progress):
    #     """Test handling of various RPCError types during reaction deletion."""
    #     chat = create_mock_chat(123, "Test Chat")
    #     cleaner_with_mocks.reaction_ids[123] = [1, 2, 3, 4]
    #
    #     # Different types of RPC errors
    #     async def mock_send_reaction(chat_id, msg_id, reaction):
    #         if msg_id == 1:
    #             raise RPCError("MESSAGE_ID_INVALID")
    #         elif msg_id == 2:
    #             raise RPCError("CHAT_ADMIN_REQUIRED")
    #         elif msg_id == 3:
    #             raise RPCError("MESSAGE_NOT_MODIFIED")
    #         # msg_id == 4 succeeds
    #
    #     cleaner_with_mocks.client.send_reaction.side_effect = mock_send_reaction
    #
    #     # Should handle all errors gracefully
    #     await cleaner_with_mocks._delete_reactions(chat, mock_progress)
    #
    #     # Should attempt all 4 reactions despite errors
    #     assert cleaner_with_mocks.client.send_reaction.call_count == 4

    @pytest.mark.asyncio
    async def test_empty_message_list_handling(self, cleaner_with_mocks, mock_progress):
        """Test handling when no messages are found."""
        chat = create_mock_chat(123, "Empty Chat")

        class AsyncIterator:
            def __init__(self, items):
                self.items = items

            def __aiter__(self):
                return self

            async def __anext__(self):
                if not self.items:
                    raise StopAsyncIteration
                return self.items.pop(0)

        # No cached IDs and search returns empty
        cleaner_with_mocks.message_ids = {}
        cleaner_with_mocks.client.search_messages = lambda *a, **kw: AsyncIterator([])

        await cleaner_with_mocks._delete_messages(chat, mock_progress)

        # Should not attempt to delete anything
        cleaner_with_mocks.client.delete_messages.assert_not_called()

        # Progress should still be updated
        mock_progress.update.assert_called()


class TestHypothesisProperties:
    """Property-based tests using Hypothesis."""

    @pytest.fixture
    def mock_client(self):
        client = AsyncMock()
        client.search_messages = AsyncMock()
        client.get_chat_history = AsyncMock()
        client.delete_messages = AsyncMock()
        client.send_reaction = AsyncMock()
        client.leave_chat = AsyncMock()
        return client

    @pytest.fixture
    def cleaner_with_mocks(self, cleaner, mock_client):
        cleaner.client = mock_client
        cleaner.console = MagicMock()
        return cleaner

    @pytest.fixture(scope="session")
    def mock_console(self):
        return MagicMock()

    # @given(
    #     chat_ids=st.lists(st.integers(min_value=1, max_value=999999), min_size=1, max_size=10),
    #     message_counts=st.lists(st.integers(min_value=0, max_value=500), min_size=1, max_size=10)
    # )
    # @settings(max_examples=20)
    # @pytest.mark.asyncio
    # async def test_message_chunking_property(self, cleaner_with_mocks, mock_progress, chat_ids, message_counts):
    #     """Property test: message deletion should always respect chunk size limit."""
    #     assume(len(chat_ids) == len(message_counts))
    #
    #     for chat_id, count in zip(chat_ids, message_counts):
    #         chat = create_mock_chat(chat_id, f"Chat {chat_id}")
    #         message_ids = list(range(1, count + 1))
    #         cleaner_with_mocks.message_ids[chat_id] = message_ids
    #
    #         await cleaner_with_mocks._delete_messages(chat, mock_progress)
    #
    #         if count > 0:
    #             # Verify all delete calls respect chunk size
    #             delete_calls = [call for call in cleaner_with_mocks.client.delete_messages.call_args_list
    #                             if call[0][0] == chat_id]
    #
    #             for call_args in delete_calls:
    #                 chunk = call_args[0][1]
    #                 assert len(chunk) <= cleaner_with_mocks.CHUNK
    #                 assert len(chunk) > 0
    #
    #             # Verify all message IDs were included
    #             all_deleted = []
    #             for call_args in delete_calls:
    #                 all_deleted.extend(call_args[0][1])
    #             assert sorted(all_deleted) == message_ids
    #
    #     cleaner_with_mocks.client.delete_messages.reset_mock()

    # @given(
    #     reaction_counts=st.integers(min_value=0, max_value=1000),
    #     error_probability=st.floats(min_value=0.0, max_value=0.5)
    # )
    # @settings(max_examples=10)
    # @pytest.mark.asyncio
    # async def test_reaction_deletion_resilience(self, cleaner_with_mocks, mock_progress,
    #                                             reaction_counts, error_probability):
    #     """Property test: reaction deletion should be resilient to errors."""
    #     chat = create_mock_chat(123, "Test Chat")
    #     cleaner_with_mocks.reaction_ids[123] = list(range(1, reaction_counts + 1))
    #
    #     error_count = 0
    #
    #     async def mock_send_reaction(chat_id, msg_id, reaction):
    #         nonlocal error_count
    #         if hash(msg_id) % 100 < error_probability * 100:
    #             error_count += 1
    #             raise RPCError("Simulated error")
    #
    #     cleaner_with_mocks.client.send_reaction.side_effect = mock_send_reaction
    #
    #     # Should complete without raising exceptions
    #     await cleaner_with_mocks._delete_reactions(chat, mock_progress)
    #
    #     # Should attempt all reactions regardless of errors
    #     if reaction_counts > 0:
    #         assert cleaner_with_mocks.client.send_reaction.call_count == reaction_counts

    @given(
        export_lines=st.lists(
            st.text(min_size=1, max_size=100), min_size=0, max_size=200
        )
    )
    @settings(max_examples=15)
    def test_export_buffer_properties(self, mock_console, export_lines):
        """Property test: export buffer should handle any valid input."""
        buffer = ExportBuffer(console=mock_console)

        # Add all lines
        for line in export_lines:
            buffer.add(Action.EXPORT_MESSAGES, line)

        with patch("builtins.open", mock_open()) as mock_file, patch(
            "telegram_cleaner.export.datetime"
        ) as mock_datetime:

            mock_datetime.now.return_value.strftime.return_value = "test_timestamp"

            buffer.flush()

            if export_lines:
                # Should create exactly one file
                assert mock_file.call_count == 1

                # Should write all lines
                handle = mock_file.return_value.__enter__.return_value
                expected_content = "\n".join(export_lines) + "\n"
                handle.write.assert_called_once_with(expected_content)
            else:
                # Should not create any files for empty input
                mock_file.assert_not_called()


def test_action_enum():
    """Test that all action values are strings."""
    for action in Action:
        assert isinstance(action.value, str)


def test_action_picker():
    """Test the ActionPicker class."""
    picker = ActionPicker()

    # Test with private chat only
    private_chat = MagicMock(spec=Chat)
    private_chat.type = ChatType.PRIVATE
    available_actions = picker.get_available_actions([private_chat])
    assert Action.EXPORT_MESSAGES in available_actions
    assert Action.EXPORT_REACTIONS in available_actions
    assert Action.DELETE_MESSAGES in available_actions
    assert Action.DELETE_REACTIONS in available_actions
    assert Action.LEAVE_GROUP not in available_actions
    assert Action.DELETE_PRIVATE_SELF in available_actions
    assert Action.DELETE_PRIVATE_BOTH in available_actions

    # Test with group chat only
    group_chat = MagicMock(spec=Chat)
    group_chat.type = ChatType.GROUP
    available_actions = picker.get_available_actions([group_chat])
    assert Action.LEAVE_GROUP in available_actions
    assert Action.DELETE_PRIVATE_SELF not in available_actions
    assert Action.DELETE_PRIVATE_BOTH not in available_actions

    # Test with both chat types
    available_actions = picker.get_available_actions([private_chat, group_chat])
    assert Action.LEAVE_GROUP in available_actions
    assert Action.DELETE_PRIVATE_SELF in available_actions
    assert Action.DELETE_PRIVATE_BOTH in available_actions


if __name__ == "__main__":
    pytest.main([__file__, "-v"])

